server:
  port: 8080

spring:
  h2:
    console:
      enabled: true

keycloak:
  realm: ${KEYCLOAK_REALM:test}
  auth-server-url:  ${KEYCLOAK_URL:https://keycloak-rhsso.apps.cluster-w47t2.w47t2.sandbox255.opentlc.com/auth}/auth
  resource: ${KEYCLOAK_CLIENT_ID:sample_application}
  public-client: ${KEYCLOAK_PUBLIC_CLIENT:true}
  ssl-required: none
  disable-trust-manager: true
  credentials:
    secret: ${CLIENT_SECRET:5880501c-02ee-4893-9a71-2c05c959bcbc}
