server:
  port: 8080

spring:
  h2:
    console:
      enabled: true

keycloak:
  realm: ${KEYCLOAK_RELM:test}
  auth-server-url:  ${KEYCLOAK_URL:https://keycloak-ansible-rhsso-operator.apps.cluster-dds8v.dds8v.sandbox1980.opentlc.com}
  resource: ${KEYCLOAK_CLIENT_ID:sample_application}
  public-client: ${KEYCLOAK_PUBLIC_CLIENT:true}
  credentials:
    secret: ${CLIENT_SECRET}
